# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_uuid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 437)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 520, 437))
        self.label.setStyleSheet("border-image: url(:/images/background.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.uuid = QtWidgets.QLineEdit(Dialog)
        self.uuid.setGeometry(QtCore.QRect(180, 120, 211, 51))
        self.uuid.setStyleSheet("QLineEdit\n"
"{\n"
"background-color:rgba(255,255,255,180);\n"
"border:none;\n"
"font: 12pt \"3ds\";\n"
"color:#55007f;\n"
"}")
        self.uuid.setInputMask("")
        self.uuid.setText("")
        self.uuid.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.uuid.setObjectName("uuid")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(120, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(14)
        self.ok.setFont(font)
        self.ok.setStyleSheet("border-image: url(:/button/边框.png);")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(270, 260, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight")
        font.setPointSize(14)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("border-image: url(:/button/边框.png);")
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "UUID"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
import apprcc_rc
import buttonrcc_rc
