# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'over.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 500)
        Dialog.setMinimumSize(QtCore.QSize(620, 500))
        Dialog.setMaximumSize(QtCore.QSize(620, 500))
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog\n"
"{border-image:url(:/images/b.png);}\n"
"\n"
"")
        self.sheng = QtWidgets.QLabel(Dialog)
        self.sheng.setGeometry(QtCore.QRect(250, 180, 131, 111))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(36)
        self.sheng.setFont(font)
        self.sheng.setStyleSheet("border-image: url(:/images/赢得01.png);")
        self.sheng.setText("")
        self.sheng.setObjectName("sheng")
        self.li = QtWidgets.QLabel(Dialog)
        self.li.setGeometry(QtCore.QRect(350, 250, 81, 81))
        self.li.setStyleSheet("border-image: url(:/images/赢得02.png);")
        self.li.setText("")
        self.li.setObjectName("li")
        self.pl = QtWidgets.QLabel(Dialog)
        self.pl.setGeometry(QtCore.QRect(60, 90, 211, 171))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(43)
        self.pl.setFont(font)
        self.pl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pl.setObjectName("pl")
        self.lose = QtWidgets.QLabel(Dialog)
        self.lose.setGeometry(QtCore.QRect(120, 320, 271, 181))
        self.lose.setStyleSheet("border-image: url(:/images/失败.png);")
        self.lose.setText("")
        self.lose.setObjectName("lose")
        self.ping = QtWidgets.QLabel(Dialog)
        self.ping.setGeometry(QtCore.QRect(200, 150, 241, 211))
        self.ping.setStyleSheet("border-image: url(:/images/ping.png);")
        self.ping.setText("")
        self.ping.setObjectName("ping")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pl.setText(_translate("Dialog", "玩家1"))
import apprcc_rc
import buttonrcc_rc
import gamercc_rc
