# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wait.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 757)
        Dialog.setMinimumSize(QtCore.QSize(1024, 757))
        Dialog.setMaximumSize(QtCore.QSize(1024, 757))
        Dialog.setStyleSheet("")
        self.join = QtWidgets.QPushButton(Dialog)
        self.join.setGeometry(QtCore.QRect(200, 170, 241, 321))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        self.join.setFont(font)
        self.join.setStyleSheet("border-image: url(:/button/结束.png);")
        self.join.setObjectName("join")
        self.cr = QtWidgets.QPushButton(Dialog)
        self.cr.setGeometry(QtCore.QRect(550, 170, 241, 321))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        self.cr.setFont(font)
        self.cr.setStyleSheet("border-image: url(:/button/结束.png);")
        self.cr.setObjectName("cr")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 757))
        self.label.setStyleSheet("border-image: url(:/images/background.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.join.raise_()
        self.cr.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.join.setText(_translate("Dialog", "加入对局"))
        self.cr.setText(_translate("Dialog", "创建对局"))
import apprcc_rc
import buttonrcc_rc
import gamercc_rc
